title: Moonrise
description: Personal portfolio

markdown: kramdown

collections: {}

permalink: /blog/:title/

# Includes & excludes
include: ["_pages"]
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll/scholar

scholar:
  style: apa
  locale: en
  source: ./_data
  bibliography: publications.bib
  bibliography_template: publication_entry
  query: "@*"
  sort_by: year
  order: descending

navigation:
  - title: about
    url: /

  - title: puzzles
    url: /puzzles/

  - title: illustrations
    url: /illustrations/

  - title: blog
    url: /blog/
